export type Aura = {
  id: string;
  name: string;
  rarity: number;
  tier: string;
  color: string;
  accent: string;
  icon: string;
  theme: string;
  description: string;
};

export const auras: Aura[] = [
  { id: 'drizzle', name: 'Drizzle', rarity: 4, tier: 'COMMON', color: '#7dd3fc', accent: '#2dd4bf', icon: '⌁', theme: 'water', description: 'A quiet shimmer caught between two raindrops.' },
  { id: 'ripple', name: 'Ripple', rarity: 6, tier: 'COMMON', color: '#a5f3fc', accent: '#67e8f9', icon: '◌', theme: 'water', description: 'The first circle a stone ever made.' },
  { id: 'dustdevil', name: 'Dust Devil', rarity: 8, tier: 'COMMON', color: '#d4a574', accent: '#fbbf24', icon: '↭', theme: 'storm', description: 'A miniature tornado with ambition issues.' },
  { id: 'sunbeam', name: 'Sunbeam', rarity: 10, tier: 'COMMON', color: '#fde68a', accent: '#fcd34d', icon: '☀', theme: 'celestial', description: 'Light that took eight minutes to say hello.' },
  { id: 'ember', name: 'Ember', rarity: 12, tier: 'COMMON', color: '#fb923c', accent: '#facc15', icon: '✦', theme: 'fire', description: 'A coal-bright spark with a heartbeat.' },
  { id: 'wildflower', name: 'Wildflower', rarity: 14, tier: 'COMMON', color: '#f9a8d4', accent: '#f472b6', icon: '✿', theme: 'nature', description: 'It bloomed where nothing asked it to.' },
  { id: 'dewdrop', name: 'Dewdrop', rarity: 16, tier: 'COMMON', color: '#bae6fd', accent: '#7dd3fc', icon: '◇', theme: 'water', description: 'Morning condensed into a single lens.' },
  { id: 'coal', name: 'Coal', rarity: 18, tier: 'COMMON', color: '#78716c', accent: '#f97316', icon: '■', theme: 'fire', description: 'A rock that swears it used to be a forest.' },
  { id: 'spark', name: 'Spark', rarity: 22, tier: 'UNCOMMON', color: '#fde047', accent: '#fbbf24', icon: '⚡', theme: 'storm', description: 'The first word electricity ever spoke.' },
  { id: 'puddle', name: 'Puddle', rarity: 24, tier: 'UNCOMMON', color: '#7dd3fc', accent: '#38bdf8', icon: '⬬', theme: 'water', description: 'A mirror that forgot it was water.' },
  { id: 'moss', name: 'Moss', rarity: 28, tier: 'UNCOMMON', color: '#86efac', accent: '#22c55e', icon: '❋', theme: 'nature', description: 'Old forest energy, patient and persistent.' },
  { id: 'pebbleskip', name: 'Pebble Skip', rarity: 30, tier: 'UNCOMMON', color: '#a8a29e', accent: '#d4d4d8', icon: '◯', theme: 'water', description: 'A stone that touched the surface six times.' },
  { id: 'pebble', name: 'Pebble', rarity: 36, tier: 'UNCOMMON', color: '#d4d4d8', accent: '#a1a1aa', icon: '⬤', theme: 'nature', description: 'A stone that remembers being a mountain.' },
  { id: 'breeze', name: 'Breeze', rarity: 45, tier: 'UNCOMMON', color: '#a7f3d0', accent: '#6ee7b7', icon: '⟿', theme: 'storm', description: 'Wind that learned to whisper names.' },
  { id: 'smoketrail', name: 'Smoke Trail', rarity: 55, tier: 'UNCOMMON', color: '#a8a29e', accent: '#e7e5e4', icon: '⌇', theme: 'fire', description: 'A question mark made of soot.' },
  { id: 'static', name: 'Static', rarity: 64, tier: 'UNCOMMON', color: '#c4b5fd', accent: '#67e8f9', icon: 'ϟ', theme: 'storm', description: 'The air around it remembers every signal.' },
  { id: 'vinesprout', name: 'Vine Sprout', rarity: 70, tier: 'UNCOMMON', color: '#84cc16', accent: '#a3e635', icon: '✾', theme: 'nature', description: 'A green sentence still being written.' },
  { id: 'heathaze', name: 'Heat Haze', rarity: 75, tier: 'UNCOMMON', color: '#fbbf24', accent: '#f97316', icon: '≈', theme: 'fire', description: 'The air bending over its own reflection.' },
  { id: 'frostwhisper', name: 'Frostwhisper', rarity: 82, tier: 'UNCOMMON', color: '#e0f2fe', accent: '#bae6fd', icon: '❄', theme: 'water', description: 'A secret told in crystals.' },
  { id: 'wavelet', name: 'Wavelet', rarity: 90, tier: 'UNCOMMON', color: '#67e8f9', accent: '#22d3ee', icon: '∿', theme: 'water', description: 'A wave that never reached the shore.' },
  { id: 'cinder', name: 'Cinder', rarity: 100, tier: 'UNCOMMON', color: '#f97316', accent: '#fb923c', icon: '⤓', theme: 'fire', description: 'The ghost of a fire that refused to leave.' },
  { id: 'dustcloud', name: 'Dust Cloud', rarity: 110, tier: 'RARE', color: '#a8a29e', accent: '#d6d3d1', icon: '☁', theme: 'storm', description: 'A weather system with no agenda.' },
  { id: 'tidepool', name: 'Tidepool', rarity: 120, tier: 'RARE', color: '#38bdf8', accent: '#818cf8', icon: '◈', theme: 'water', description: 'A miniature ocean orbiting a hidden moon.' },
  { id: 'emberstorm', name: 'Emberstorm', rarity: 130, tier: 'RARE', color: '#fb923c', accent: '#f97316', icon: '✶', theme: 'fire', description: 'A blizzard running the wrong season.' },
  { id: 'bramblethorn', name: 'Bramblethorn', rarity: 150, tier: 'RARE', color: '#65a30d', accent: '#84cc16', icon: '✸', theme: 'nature', description: 'A thicket that grew teeth overnight.' },
  { id: 'glowbug', name: 'Glowbug', rarity: 180, tier: 'RARE', color: '#bef264', accent: '#a3e635', icon: '◉', theme: 'nature', description: 'A lantern with legs and opinions.' },
  { id: 'wildgrowth', name: 'Wildgrowth', rarity: 220, tier: 'RARE', color: '#22c55e', accent: '#4ade80', icon: '☘', theme: 'nature', description: 'Photosynthesis with a caffeine problem.' },
  { id: 'honeycomb', name: 'Honeycomb', rarity: 256, tier: 'RARE', color: '#fbbf24', accent: '#fb7185', icon: '⬡', theme: 'nature', description: 'Sweet geometry with a golden pulse.' },
  { id: 'flameheart', name: 'Flameheart', rarity: 280, tier: 'RARE', color: '#ef4444', accent: '#fb923c', icon: '♥', theme: 'fire', description: 'A cardiac muscle made of pure combustion.' },
  { id: 'thunderhead', name: 'Thunderhead', rarity: 340, tier: 'RARE', color: '#818cf8', accent: '#6366f1', icon: '☇', theme: 'storm', description: 'A cloud that swallowed a cathedral.' },
  { id: 'rainblessed', name: 'Rainblessed', rarity: 350, tier: 'RARE', color: '#7dd3fc', accent: '#a78bfa', icon: '☂', theme: 'water', description: 'Every drop carries a different wish.' },
  { id: 'stormcrown', name: 'Stormcrown', rarity: 400, tier: 'RARE', color: '#6366f1', accent: '#818cf8', icon: '♔', theme: 'storm', description: 'Worn by a king who ruled lightning.' },
  { id: 'mistsong', name: 'Mistsong', rarity: 420, tier: 'RARE', color: '#a5b4fc', accent: '#c7d2fe', icon: '♩', theme: 'water', description: 'Fog that learned to hum in four-part harmony.' },
  { id: 'pyre', name: 'Pyre', rarity: 480, tier: 'RARE', color: '#dc2626', accent: '#f97316', icon: '♨', theme: 'fire', description: 'A flame that burns for someone it never met.' },
  { id: 'ashveil', name: 'Ashveil', rarity: 520, tier: 'RARE', color: '#a8a29e', accent: '#d6d3d1', icon: '⬢', theme: 'fire', description: "Grey silk woven from a volcano's exhale." },
  { id: 'starlightecho', name: 'Starlight Echo', rarity: 560, tier: 'RARE', color: '#c4b5fd', accent: '#e9d5ff', icon: '✧', theme: 'celestial', description: 'Light that arrived ten thousand years late.' },
  { id: 'starfall', name: 'Starfall', rarity: 650, tier: 'RARE', color: '#fde68a', accent: '#fcd34d', icon: '✦', theme: 'celestial', description: 'A star that chose the ground over the sky.' },
  { id: 'tempest', name: 'Tempest', rarity: 700, tier: 'EPIC', color: '#3b82f6', accent: '#60a5fa', icon: '🌀', theme: 'storm', description: 'A storm that argues with itself.' },
  { id: 'aurora', name: 'Aurora', rarity: 777, tier: 'EPIC', color: '#5eead4', accent: '#a7f3d0', icon: '∿', theme: 'celestial', description: 'Polar light folded into a single silhouette.' },
  { id: 'nullspace', name: 'Nullspace', rarity: 850, tier: 'EPIC', color: '#64748b', accent: '#94a3b8', icon: '∅', theme: 'void', description: 'The gap between two thoughts.' },
  { id: 'rootweave', name: 'Rootweave', rarity: 900, tier: 'EPIC', color: '#84cc16', accent: '#4ade80', icon: '❧', theme: 'nature', description: "A forest's nervous system, exposed." },
  { id: 'flameforged', name: 'Flameforged', rarity: 1100, tier: 'EPIC', color: '#ef4444', accent: '#f97316', icon: '⚒', theme: 'fire', description: 'Hammered in a furnace that burns sideways.' },
  { id: 'magmavein', name: 'Magma Vein', rarity: 1200, tier: 'EPIC', color: '#dc2626', accent: '#fb923c', icon: '⤓', theme: 'fire', description: 'The earth\'s circulatory system, leaking.' },
  { id: 'galeforce', name: 'Galeforce', rarity: 1400, tier: 'EPIC', color: '#60a5fa', accent: '#93c5fd', icon: '⟿', theme: 'storm', description: 'Wind that earned a rank and a serial number.' },
  { id: 'abyssalecho', name: 'Abyssal Echo', rarity: 1600, tier: 'EPIC', color: '#475569', accent: '#64748b', icon: '⊙', theme: 'void', description: 'A sound that bounced off nothing.' },
  { id: 'coralcrown', name: 'Coral Crown', rarity: 1700, tier: 'EPIC', color: '#fb7185', accent: '#f9a8d4', icon: '♛', theme: 'water', description: 'Worn by a king who never surfaced.' },
  { id: 'bloomstorm', name: 'Bloomstorm', rarity: 2000, tier: 'EPIC', color: '#4ade80', accent: '#f472b6', icon: '✺', theme: 'nature', description: 'A hurricane made entirely of petals.' },
  { id: 'voidwalker', name: 'Voidwalker', rarity: 2400, tier: 'EPIC', color: '#94a3b8', accent: '#e2e8f0', icon: '◌', theme: 'void', description: 'Something that learned to walk between seconds.' },
  { id: 'phoenixdown', name: 'Phoenix Down', rarity: 2600, tier: 'EPIC', color: '#fb923c', accent: '#fde047', icon: '🜂', theme: 'fire', description: 'A feather that still remembers the fire.' },
  { id: 'infernoheart', name: 'Inferno Heart', rarity: 3100, tier: 'EPIC', color: '#dc2626', accent: '#fb923c', icon: '♥', theme: 'fire', description: 'A cardiac muscle made of pure combustion.' },
  { id: 'leviathanwake', name: "Leviathan's Wake", rarity: 3200, tier: 'EPIC', color: '#0ea5e9', accent: '#38bdf8', icon: '〜', theme: 'water', description: 'The ripple a sleeping god left behind.' },
  { id: 'verdantecho', name: 'Verdant Echo', rarity: 3900, tier: 'EPIC', color: '#16a34a', accent: '#4ade80', icon: '❧', theme: 'nature', description: 'The forest repeating a word it forgot.' },
  { id: 'nebulaveil', name: 'Nebula Veil', rarity: 4000, tier: 'EPIC', color: '#c4b5fd', accent: '#ddd6fe', icon: '⬬', theme: 'celestial', description: 'A nursery for stars, worn as a curtain.' },
  { id: 'cycloneveil', name: 'Cyclone Veil', rarity: 4800, tier: 'EPIC', color: '#3b82f6', accent: '#60a5fa', icon: '◎', theme: 'storm', description: 'A tornado wearing a disguise.' },
  { id: 'entropy', name: 'Entropy', rarity: 5500, tier: 'LEGENDARY', color: '#64748b', accent: '#cbd5e1', icon: '⧖', theme: 'void', description: 'The universe forgetting where it put things.' },
  { id: 'sunflare', name: 'Sunflare', rarity: 6500, tier: 'LEGENDARY', color: '#fde047', accent: '#fb923c', icon: '☼', theme: 'fire', description: 'A star in the moment before it becomes light.' },
  { id: 'cosmicpulse', name: 'Cosmic Pulse', rarity: 7000, tier: 'LEGENDARY', color: '#a78bfa', accent: '#c4b5fd', icon: '✦', theme: 'celestial', description: 'The heartbeat of something very far away.' },
  { id: 'moonlit', name: 'Moonlit', rarity: 12000, tier: 'LEGENDARY', color: '#bae6fd', accent: '#c4b5fd', icon: '☾', theme: 'celestial', description: 'Silver silence from the far side of sleep.' },
  { id: 'ashencrown', name: 'Ashen Crown', rarity: 15000, tier: 'LEGENDARY', color: '#a8a29e', accent: '#f97316', icon: '♔', theme: 'fire', description: 'Forged in the ruins of a burned kingdom.' },
  { id: 'astralcrown', name: 'Astral Crown', rarity: 22000, tier: 'LEGENDARY', color: '#c4b5fd', accent: '#e9d5ff', icon: '♛', theme: 'celestial', description: 'Set with stones from constellations that no longer exist.' },
  { id: 'neonbloom', name: 'Neon Bloom', rarity: 28000, tier: 'MYTHIC', color: '#4ade80', accent: '#22d3ee', icon: '✺', theme: 'nature', description: 'A flower engineered by a future that never arrived.' },
  { id: 'abyssalcrown', name: 'Abyssal Crown', rarity: 40000, tier: 'MYTHIC', color: '#475569', accent: '#64748b', icon: '♚', theme: 'void', description: 'Worn by whatever lives below the floorboards of reality.' },
  { id: 'chronoshift', name: 'Chronoshift', rarity: 50000, tier: 'MYTHIC', color: '#f0abfc', accent: '#fda4af', icon: '⟳', theme: 'void', description: 'Every possible roll, visible for one frame.' },
  { id: 'pyroclasm', name: 'Pyroclasm', rarity: 70000, tier: 'MYTHIC', color: '#dc2626', accent: '#fbbf24', icon: '🌋', theme: 'fire', description: 'A mountain that finally said what it meant.' },
  { id: 'deepcurrent', name: 'Deep Current', rarity: 125000, tier: 'EXOTIC', color: '#22d3ee', accent: '#2563eb', icon: '≈', theme: 'water', description: 'Pressure from an ocean no map can find.' },
  { id: 'gaiaspulse', name: "Gaia's Pulse", rarity: 200000, tier: 'EXOTIC', color: '#16a34a', accent: '#4ade80', icon: '❧', theme: 'nature', description: 'The planet breathing through a single vein.' },
  { id: 'blackrain', name: 'Black Rain', rarity: 300000, tier: 'EXOTIC', color: '#64748b', accent: '#38bdf8', icon: '╱', theme: 'storm', description: 'A storm cloud distilled into a falling line.' },
  { id: 'nova', name: 'Nova', rarity: 400000, tier: 'EXOTIC', color: '#fde047', accent: '#fb923c', icon: '✦', theme: 'celestial', description: 'A star introducing itself to the neighborhood.' },
  { id: 'hollowstar', name: 'Hollow Star', rarity: 600000, tier: 'DIVINE', color: '#94a3b8', accent: '#cbd5e1', icon: '☆', theme: 'void', description: 'A star that burned out but kept its shape.' },
  { id: 'seraphim', name: 'Seraphim', rarity: 750000, tier: 'DIVINE', color: '#fef08a', accent: '#fb7185', icon: '✧', theme: 'celestial', description: 'A wingbeat heard at the edge of creation.' },
  { id: 'singularity', name: 'Singularity', rarity: 1500000, tier: 'DIVINE', color: '#e2e8f0', accent: '#f97316', icon: '⊙', theme: 'void', description: 'The center of a story with no outside.' },
  { id: 'supernova', name: 'Supernova', rarity: 2000000, tier: 'DIVINE', color: '#fbbf24', accent: '#fb7185', icon: '✸', theme: 'celestial', description: 'A farewell letter written in light.' },
  { id: 'pulsar', name: 'Pulsar', rarity: 4000000, tier: 'DIVINE', color: '#a78bfa', accent: '#c4b5fd', icon: '◉', theme: 'celestial', description: 'A lighthouse for ships that sail between galaxies.' },
  { id: 'quasar', name: 'Quasar', rarity: 7000000, tier: 'TRANSCENDENT', color: '#c4b5fd', accent: '#fde047', icon: '✹', theme: 'celestial', description: 'An engine that runs on discarded physics.' },
  { id: 'worldeater', name: 'World Eater', rarity: 10000000, tier: 'TRANSCENDENT', color: '#fb7185', accent: '#facc15', icon: '◉', theme: 'fire', description: 'A horizon that decided to become hungry.' },
  { id: 'starforge', name: 'Starforge', rarity: 15000000, tier: 'TRANSCENDENT', color: '#fde047', accent: '#fb923c', icon: '⚒', theme: 'celestial', description: 'The anvil where new suns are hammered flat.' },
  { id: 'greenhouse', name: 'Greenhouse', rarity: 25000000, tier: 'TRANSCENDENT', color: '#4ade80', accent: '#fef08a', icon: '♧', theme: 'nature', description: 'The first garden at the end of the universe.' },
  { id: 'galaxyheart', name: 'Galaxy Heart', rarity: 40000000, tier: 'TRANSCENDENT', color: '#a78bfa', accent: '#f0abfc', icon: '❤', theme: 'celestial', description: 'A cardiac muscle with a billion-year rhythm.' },
  { id: 'eventhorizon', name: 'Event Horizon', rarity: 100000000, tier: 'ABSOLUTE', color: '#f8fafc', accent: '#22d3ee', icon: '◍', theme: 'void', description: 'Nothing returns from this discovery unchanged.' },
  { id: 'cosmiccrown', name: 'Cosmic Crown', rarity: 200000000, tier: 'ABSOLUTE', color: '#c4b5fd', accent: '#fde047', icon: '♛', theme: 'celestial', description: 'Worn by whoever wins the last argument with entropy.' },
  { id: 'solstice', name: 'Solstice', rarity: 500000000, tier: 'ABSOLUTE', color: '#fef08a', accent: '#f8fafc', icon: '✹', theme: 'celestial', description: 'The rarest light the simulation is allowed to render.' },
];
